### ISSUE TITLE
Swap SDL_Joystick for SDL_GameController?

### ISSUE THREAD

**Issue by jared6502** [RetroAchievements/RALibretro#195]
Some input devices are currently not usable in RALibretro due to not being recognized by the SDL_GameController functions. A particular example of this is when trying to use a vJoy device. In my case it is being used to receive inputs from an SNES controller. SDL_GameController doesn't recognize the vJoy virtual joystick device at all, which prevents it from being mapped to any buttons. If, however, I replace the SDL_GameController functions and events with SDL_Joystick functions and events, as well as increase the maximum number of buttons that are monitored to accomodate my particular setup, the buttons can be mapped and function properly.

**Comment by Jamiras** [comment]
As best as I can tell, `SDL_GameController` is the better API to use. It seems to supercede `SDL_Joystick`. I'm not really familiar with SDL in general, and didn't write the code to being with, but I know there's [a mapping file](https://github.com/RetroAchievements/RALibretro/blob/develop/src/components/GameControllerDB.inl). Perhaps it's just out-of-date?

**Comment by jared6502** [comment]
When I was looking into this to figure out what to change, I'd read that SDL_GameController was introduced to try and replace SDL_Joystick for normal use, since it's simpler to work with and has preconfigured controller mappings, but that it uses SDL_Joystick internally for everything anyway.

In the particular case that brought this up, I was trying to use a controller adapter I made, so there is no chance it would have ever been in the mapping database. Having the ability to add new mappings without rebuilding the whole program might be enough to solve my specific issue without modifying anything else.

**Comment by leiradel** [comment]
The game controller API is built on top of the joystick API, and is not meant to replace it. It's just a way to automatically map a physical gamepad to a idealized SDL gamepad that looks like a Xbox 360 gamepad.

The physical buttons, directional pad, analog axis, and triggers will be mapped to that idealized gamepad, and will be ready to use without needing any input mapping settings in the application. The downside is that physical gamepads won't always map 1:1 to the SDL gamepad, and that mappings for some gamepads maybe missing from the [mappings database](https://github.com/gabomdq/SDL_GameControllerDB).

In RALibretro, the gamepad database is compiled into the executable in [`Input.cpp`](https://github.com/RetroAchievements/RALibretro/blob/develop/src/components/Input.cpp), so any updates to the database require a new release. I think RALibretro should be changed to read the database from a file instead, so that users could update the database by just copying a new file over the old one, and add nonexistent mappings by appending lines to it. These mappings can be produces by tools like [SDL2 Gamepad Tool](https://generalarcade.com/gamepadtool/) by General Arcade. SDL2 also has such a tool that can be compiled from source code.

The SDL2 Gamepad Tool has a button that will copy the generated mapping to an environment variable that SDL2 checks, so it's possible to add ad-hoc mappings to SDL2 applications without changing anything. This can solve @jared6502 's issue, but the mapping must be generated and copied everytime so it's really a short term solution.

**Comment by Jamiras** [comment]
> Having the ability to add new mappings without rebuilding the whole program might be enough to solve my specific issue without modifying anything else.

This will be available in 1.3. If it solves your issue, please close this ticket.
