### ISSUE TITLE
Audio plays, no graphics

### ISSUE THREAD

**Issue by ghost** [RetroAchievements/RALibretro#200]
Both SNES and GBA cores are giving me no video.  Same ROMS work fine with RAzSNES9x and RetroArch, so the problem has to be with RALibRetro.  ROM I want to work is Shiren the Wanderer (Fushigi no Dungeon 2 - Fuurai no Shiren).

I've tried fixes for 8 hours on my own with no results, including changing settings and attempting to recompile RALibRetro (the instructions don't work for me; msys2 mysteriously installs gcc somewhere that isn't in my path and won't tell me where it is.)

I'm rather frustrated.

**Comment by Jamiras** [comment]
It's clearly something on your machine. This is official 1.2.1 release with latest Snes9x core and default settings:

![image](https://user-images.githubusercontent.com/32680403/85211662-92123b00-b308-11ea-86b3-25686d944b1c.png)

I'm not saying it's not RALibretro, but I can't reproduce.

Regarding building RALibretro - the msys build is often neglected as the primary development environment is visual studio, although it sounds like you're having an environmental issue instead of a build issue.

**Comment by PsyMar** [comment]
I have the 1.2.0 version.  Where do I get 1.2.1?

**Comment by PsyMar** [comment]
The about log gives me (towards the end):

[ERROR] [COR] Unimplemented env call: GET_AUDIO_VIDEO_ENABLE (47) (47)
[ERROR] [OGL] Error in Gl::genTextures:
[ERROR] [OGL]   INVALID_ENUM

/shrug

**Comment by PsyMar** [comment]
Just realized OGL is probably OpenGL so I'm updating my display driver.  Hope it helps...

**Comment by Jamiras** [comment]
Yes, the "INVALID_ENUM" error is coming from the OpenGL library. `Gl::genTextures` is just a wrapper around `glGenTextures` that checks for (and logs) the error code. I don't know why `glGenTextures` would be causing a `GL_INVALID_ENUM` error, so I can't recommend anything to try that might fix it.

Near the top of the log file you should see the OpenGL version detected:
```
[INFO ] [APP] Got OpenGL 2.1
```

**Comment by PsyMar** [comment]
Yep, it shows OpenGL 2.1.  I think it's somehow getting stuck in an infinite loop trying to adjust the size of the canvas, possibly something to do with floating points?  I'll attach the log.
[log.txt](https://github.com/RetroAchievements/RALibretro/files/4808865/log.txt)
