### ISSUE TITLE
Turbo mode disables sound - intended feature?

### ISSUE THREAD

**Issue by JKoppel93** [RetroAchievements/RALibretro#243]
I am currently using the DesMume core and using the turbo mode feature disables all sound. Is this intended?

**Comment by Jamiras** [comment]
Yes. This is intended.

Turbo mode is effectively running five frames of emulation for every frame rendered. Should it also only spit out every fifth frame of audio? I don't imagine that would be a very pleasant sound. And only using every fifth sample from all five frames would create a very high-pitched sound.

What would you expect to hear while fast-forwarding? If you want to enjoy the game's audio, you'd be best off listening to it at normal speed.

Additionally, depending on the complexity of the system you're emulating and your machine specs, only rendering every fifth frame may only provide a 2x speed increase instead of a 5x speed increase, so any sort of scaling would have to adapt to the actual speedup the core is able to achieve.

**Comment by Jamiras** [comment]
I looked into the RetroArch implementation for this, and basically they just write audio data to the sound device as quickly as they can. If the sound device can't accept any more audio at the current time, it's just discarded. This results in small chunks of audio from each frame being played. It should be fairly simple to do something similar in RAlibretro.
