### ISSUE TITLE
Overlay integration issues

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RALibretro#3]
_From @JuliaWolska on February 27, 2018 20:57_

Propably not properly optimized.
- overlay menu flashes randomly (becoming transparent for a split of the second)
- random display glitches in the overlay menu
- values in memory inspector and achievement editor are not updating fluently, and this applies both to memory view, hit counts and contents of all fields in the editor

_Copied from original issue: meleu/RALibretro#20_

**Comment by leiradel** [comment]
Can this be closed?

**Comment by Jamiras** [comment]
There's still a bit of flicker if you leave the overlay open because the SDL buffer is rendered for every frame even when the overlay is visible, and sometimes the overlay doesn't paint over it before it's displayed.

I don't expect a fix is coming any time soon. I'll let you decide if you want to keep this open for that issue, open another issue, or just ignore it.

**Comment by leiradel** [comment]
I wonder if removing the drawing code when the overlay is active can solve or at least improve this... Is there a way to know when the overlay is active?

**Comment by Jamiras** [comment]
Internally, the `m_nTransitionState` will be `TS_HOLD`, but that's not even exposed from the class, let alone through the DLL. I'll give it a try in the next couple days.

**Comment by Jamiras** [comment]
Disabling `video->render` while the overlay is visible does fix the issue.

**Comment by salvadorc17** [comment]
Im having some issue with overlay popups, must be related with this issue.

![ralibretro1](https://user-images.githubusercontent.com/13541889/40592776-a088e0b2-61e8-11e8-929b-b51880cae3c0.png)
