### ISSUE TITLE
Remove core DLLs from the repository

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#38]
#37 provides a script to fetch cores on Windows, so the core DLLs in the `develop` branch are bloating the size of the repository for no reason.

The best would be to provide a better way to fetch dependencies and get rid of all of them, ignoring the entire `bin` directory.

**Comment by leiradel** [comment]
I believe they were put there to make everything work out-of-the-box, and that the fetch script exists just to update them. @meleu can you confirm this?

**Comment by rzumer** [comment]
If that's really important, then please consider bundling `wget` and `unzip` instead. I don't think that vendoring cores is a good idea, considering their size.

**Comment by leiradel** [comment]
I'll leave @meleu @Jamiras and @GameDragon2k decide what to do about this. My development machine runs Linux.

I just don't think removing them from the repo and adding instructions to the README to make developers run a script before start working with it is not much different in practice.

**Comment by rzumer** [comment]
The difference is that the fetch script will always download up-to-date versions of the cores, while vendored cores would need to be updated regularly in the repository, which involves maintenance work and pollutes the history, and means that in order to get a full (deep) copy of the repository, one will end up downloading every set of cores in history. Someone who reads the `README` before cloning will know to fetch a shallow clone, but not everyone does that, and migrations or other operations that require the full repository history will also likely cause problems.

**Comment by leiradel** [comment]
I think they being in the `bin` folder also means that they are the "good" set, that have been tested and are known to work. I'll let the other devs decide.

**Comment by Jamiras** [comment]
I agree that having binaries in the repository is unnecessary bloat, and one of the few things git doesn't do very well. Right now the bin directory is 63MB - fbalpha being more than half of that. Because git is a distributed repository, that 63MB has to be downloaded every time someone clones the repository. If we decide we want a new build of fbalpha, that's an automatic 35MB more. The previous one is still in the history, and therefore has to be available locally in case you wanted to switch to an older commit.

In order to nuke these binaries from the repository, we have to rewrite the history without them. That's fairly trivial to do, but it will break any local checkouts you have of the affected branch or anything that was branched off the affected branch. As these files are in the `develop` branch, and `develop` is the default branch, that means pretty much everyone is affected. Any local `develop` checkouts, or any local branches made off `develop` after May 1st will be broken after this change. The commits after May 1st that have been pushed to the server will be rewritten without the offending binaries. A fresh clone will still contain the same code, but existing clones will suffer from a "detached HEAD" problem.

In my opinion, it would be beneficial to remove these files from the repository. It is my recommendation that anyone working with the repository clone a fresh copy after the purge. As such, if anyone has any non-committed code they want to keep, consider pushing it now.

Let me know if you have any concerns. I won't do anything until at least next weekend.

**Comment by leiradel** [comment]
@Jamiras ok, could announce in the appropriate forums so everyone has time to comply? I don't think this will affect anyone besides us, but it doesn't hurt to be sure.

**Comment by rzumer** [comment]
People should be able to rebase their changesets either way.

**Comment by Jamiras** [comment]
> could announce in the appropriate forums so everyone has time to comply?

What would the appropriate forum be? It seems like the target audience would get the notification about this issue being updated just from watching this repository. I'm not even sure what the appropriate Discord channel would be. It's not really #rasuite or #raemus. So #devs?

**Comment by rzumer** [comment]
Have you encountered issues due to the use of nightly builds before, or is this hypothetical?

**Comment by leiradel** [comment]
@meleu is right, the libretro cores don't follow a strict release cycle. There were situations where a core update would lead to lost save games, because the code that deals with save states had changed in incompatible ways and released without warning.

Although it's rare to have that kind of issue, I'd rather still have a known "good" set of cores. If the repository is not a good place for them, we should find another place. We can't assume nightly core builds are always ok and stick to the "good" set.

**Comment by rzumer** [comment]
Can you please provide a reference for a case where core updates led to lost save games? Was it resolved afterwards, between stable releases? Did save states get overwritten automatically on read?

I don't consider save states to be a critical system that warrants holding back improvements and fixes to a core, and I don't think that auditing every one of them to guarantee that no breaking change was pushed to a deployment version is reasonable, but I would recommend documenting the deployment process somewhere and packaging stable releases, not nightly builds. The reason why the fetch script operates on nightly builds is because stable builds do not include individual core packages.

**Comment by leiradel** [comment]
> Can you please provide a reference

I'm afraid references are lost in IRC/Discord chat histories. The issues weren't fixed because they weren't bugs, they were made in the upstream repos and caused compatibility issues with the save states when the changes were updated in the cores. The main problem is that the cores are not kept up-to-date with the upstream repos, updates are made from time to time and incorporate lots of changes in one shot.

> packaging stable releases

There are no stable releases of libretro cores, only nightly builds. Our "good" core set would be the what we think are stable releases for RALibretro.

> I don't consider save states to be a critical system

Save states is a very important feature, I sure don't want to have angry users opening issues because their save states don't work anymore.

**Comment by rzumer** [comment]
From what I understand, save states were not "lost", they were simply rendered incompatible with newer versions of some cores. In that case, rolling back is not a major issue, but users will eventually have to migrate. I don't know that we can take responsibility for core maintainers following best practices, and we can't hold back updates forever. So in practice I don't see much difference between deploying fresh core builds at every release and holding them back for some arbitrary amount of time.

**Comment by leiradel** [comment]
> save states were not "lost"

End users won't care what the real issue was, they will be unable to load their save games.

> rolling back is not a major issue

I wouldn't count on end-users locating the last known "good" core and updating RALibretro by hand.

> I don't know that we can take responsibility for core maintainers following best practices

And we can't make our end-users lives worse because they don't follow best practices.

> In order for a list of "stable" cores to be useful and reliable, we would need acceptance tests covering every important feature exhaustively

We don't need to go overboard with this. When a cool feature is released or an important bug is fixed, we can just wait a couple of weeks after the core is available and see if there are road blocks. Of course if one has enough time to make such tests, I'm all in for that.

> which is not much better than trusting the core maintainers

It's not much a question of trust. I'm positive they do their best trying to maintain their ports of the upstream emulators, but when you only have time to update the core once an year, the original emulator may already changed the save state format and dropped the compatibility code that loads the previous format so the core just can't load the previous format after one single update.

Again, this has happened before, and in the current state of affairs, can happen again. I don't think exposing RetroAchievements end-users with the holes we have in our release process as a hole is the best approach, hence my stance about having a known "good" set of cores, and updating them with care.

**Comment by rzumer** [comment]
>End users won't care what the real issue was, they will be unable to load their save games.

It's a huge difference! You can easily roll back to a previous version of the affected core (if this is a legitimate bug) or direct affected users to do this themselves. This is not the same as losing or corrupting files, which *would* be a major issue! In any case, the situation you describe seems preferable to sticking with an older version that is potentially buggier in unpredictable ways, as well as less accurate/compatible.

>I wouldn't count on end-users locating the last known "good" core and updating RALibretro by hand.

Is it difficult to provide a link to the RetroArch buildbot? It includes several older "stable" versions as backup. In addition, deploying a hotfix version to correct any critical issue is possible and users who are not capable of following a link and downloading files on their own could... follow another link and download some other files? I think we should expect some level of intelligence from end users.

>And we can't make our end-users lives worse because they don't follow best practices.

Again, it sounds like the situation you brought up was a one-time issue involving a single core, and as you said, it was never rolled back. So you'd be making users' lives worse either way.

>We don't need to go overboard with this.

As a user, I would not trust some arbitrary tests performed at random times by another random user without any standards any more than a core maintainer's own testing. I don't feel that there's any benefit to holding back updates without serious guarantees about stability.

I will let others voice their thoughts on these issues, but your concerns about stability are backed only by an example of a breaking change that does not affect the integrity of user files, and would only be delayed by holding updates back. Part of using a libretro-based frontend is yielding control of the cores to their maintainers; we can't fork the repositories (and we all know that doing so doesn't guarantee being bug- or crash-free), and holding on to old versions for the sake of stability can potentially have the adverse effect, or compromise on compatibility and performance, without exhaustive acceptance testing, which is unrealistic for a project of this scope.

**Comment by Jamiras** [comment]
Did we come to a verdict on this? @ScottFromDerby seems to want to keep them where they are to keep the "barrier for entry" low. @meleu suggested a new git repo for the binaries (not really an improvement). #37 downloads them from the nightly builds.

It seems like the ideal solution would be to put a package of approved cores on a host somewhere. Then the user could download/compile the executable separately from the cores. This is similar to how RAProject64 manages its plugins. I'd even go so far as to just document the behavior rather than have a script do it.

**Comment by rzumer** [comment]
The shell script in master right now downloads nightly builds. #37 is a port.

**Comment by meleu** [comment]
I want to solve this issue soon. And I would like to know what are the drawbacks of creating a dedicated repo for us to put the cores (windows 32bits builds only).

My plan is to update the cores every time we release a new version of RALibretro.

IMO creating another repo is a good approach cause we could have a safe way to get older builds if something breaks. The [libretro's nightly website](https://buildbot.libretro.com/nightly/windows/x86/) doesn't keep older builds of the cores for downloading and users would need to build them from source to get them.

Opinions?

**Comment by leiradel** [comment]
> And I would like to know what are the drawbacks of creating a dedicated repo for us to put the cores (windows 32bits builds only).

I only know git superficially, so pardon my ignorance, but how does that improve what we have now if the two repositories will walk hand-in-hand?

Can't we have a `RALibretro.zip` file available at RetroAchievements with the executable, the necessary DLLs, and all supported cores bundled?

**Comment by Jamiras** [comment]
The problem this is trying to address is git is a distributed system, and keeps history for everything. So that 40MB FBA core that's in the repository now is downloaded to everyone who clones the repository even if it's been replaced a dozen times already - which would of course also down the newest version and the 10 intermediate versions.

As I mentioned in my last comment: using a separate git repository does nothing to address the problem.

The cores _are_ in the official release package. But we still need some way to indicate when we move to an updated core so people can use it until the next release. And we might want to know which versions of the cores were supported in each released version - which could be handled just by archiving the release packages.

**Comment by meleu** [comment]
> I only know git superficially, so pardon my ignorance, but how does that improve what we have now if the two repositories will walk hand-in-hand?

1. The main issue here is that RALibretro contributors need to download big files when cloning the repo, and those files are not always necessary for the feature/fix they'll work.
2. If we update the cores here on RALibretro's repo, the size of the repo will continuously grow with different versions of the cores in the commit history.
3. The separated repo only for the core binaries is not intended to be cloned, but just a way to keep older versions of the cores.

**Comment by rzumer** [comment]
> As I mentioned in my last comment: using a separate git repository does nothing to address the problem.

I agree that `git` is not a good solution to host a set of cores to distribute, it would make it a little better, since it is possible to specify a depth level for submodules. At least by default it would be possible to only fetch the cores if they are needed, and only the latest versions.

If all that matters is having that set of cores hosted somewhere, then the RA server seems best.

**Comment by rzumer** [comment]
This is tangentially related, but assuming at least some of the cores are licensed under the GPL, currently we are not following the terms for distribution:

```
You may copy and distribute the Program (or a work based on it, under Section 2) in object code or executable form under the terms of Sections 1 and 2 above provided that you also do one of the following:

a) Accompany it with the complete corresponding machine-readable source code, which must be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange; or,

b) Accompany it with a written offer, valid for at least three years, to give any third party, for a charge no more than your cost of physically performing source distribution, a complete machine-readable copy of the corresponding source code, to be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange; or,

c) Accompany it with the information you received as to the offer to distribute corresponding source code. (This alternative is allowed only for noncommercial distribution and only if you received the program in object code or executable form with such an offer, in accord with Subsection b above.)
```

**Comment by Jamiras** [comment]
With #103, cores can now be downloaded/updated from the nightly buildbot **just like RetroArch**. The dlls have been removed from the current `develop` branch, but still have to exist for current `master`.

I'm undecided whether or not the history should be rewritten to completely eliminate them from the repository, so I'm going to leave this open.
