### ISSUE TITLE
Master System games link to Mega Drive

### ISSUE THREAD

**Issue by ViperZang** [RetroAchievements/RALibretro#65]
In the `Unrecognized Title` window when trying to link a Master System game using the `Genesis Plus GX` core, the dropdown list show SMS as well as Mega Drive and GameBoy Color games.

I tried making a new entry for the SMS `Earthworm Jim` but when I typed it in, it linked to the Mega Drive version instead.
I tried making a new entry using `Earthworm Jim SMS` to differentiate the two, but it still linked to Mega Drive.
I had to use RAMeka to get it to properly link.

**Comment by meleu** [comment]
@ViperZang could you please make a test using picodrive?

**Comment by meleu** [comment]
## Long story short

I think the problem exists only in Genesis Plus GX and happens because [its `retro_get_memory_size()`](https://github.com/nadavbh12/Genesis-Plus-GX/blob/f66676d86877e52e20d011fdc36148e8745ac5a8/libretro/libretro.c#L2059) makes no distinction of the system being emulated when returning the memory size.

## My reasoning

The heuristic [happening here](https://github.com/RetroAchievements/RALibretro/blob/4907df8acd08ee893c34f228f4a4e752267959c2/src/Emulator.cpp#L148-L164) makes me believe that RALibretro recognizes the ROM as a Master System game when all these conditions are true:
1. using picodrive or Genesis Plus GX **AND**
2. the system RAM memory size is equal to 8192 bytes (`0x2000`) **AND**
3. the file extension is not `.gg`.

The [picodrive's `retro_get_memory_size()`](https://github.com/libretro/picodrive/blob/03f663dd1a65f11cadbd51bd4389dc82581f2f23/platform/libretro/libretro.c#L1159) seems to try to guess the system being emulated (at least [this line of code](https://github.com/libretro/picodrive/blob/03f663dd1a65f11cadbd51bd4389dc82581f2f23/platform/libretro/libretro.c#L1182), with a variable named `PAHW_SMS`, makes me believe it's trying to figure if the content is a Sega Master System game).

The [Genesis Plus GX's `retro_get_memory_size()`](https://github.com/nadavbh12/Genesis-Plus-GX/blob/f66676d86877e52e20d011fdc36148e8745ac5a8/libretro/libretro.c#L2059) doesn't seem to have such logic. Looks like it [always return `0x10000` (65536 bytes)](https://github.com/nadavbh12/Genesis-Plus-GX/blob/f66676d86877e52e20d011fdc36148e8745ac5a8/libretro/libretro.c#L2090).

Therefore, when launching a Master System game with Genesis Plus GX the condition 2 described above will be false (RAM memory size different than `0x2000`).

**Comment by leiradel** [comment]
> The [Genesis Plus GX's `retro_get_memory_size()`](https://github.com/libretro/Genesis-Plus-GX/blob/f66676d86877e52e20d011fdc36148e8745ac5a8/libretro/libretro.c#L2059) doesn't seem to have such logic. Looks like it [always return `0x10000` (65536 bytes)](https://github.com/nadavbh12/Genesis-Plus-GX/blob/f66676d86877e52e20d011fdc36148e8745ac5a8/libretro/libretro.c#L2090).

Can we test for other file extensions to make the heuristic more robust?

**Comment by meleu** [comment]
@leiradel sorry dude, I was looking at a wrong fork :sweat:, not the actual libretro's repo. Actually [there's a logic that seems to try to guess the system being emulated](https://github.com/libretro/Genesis-Plus-GX/blob/f5eed5133101999e1f6f04d2240ae77bb891adb9/libretro/libretro.c#L2470) (BTW, the git blame says it was added by you).

I'll make some tests tonight.

**Comment by leiradel** [comment]
So we shouldn't have this issue, right? Or `system_hw` doesn't have the correct value?

**Comment by meleu** [comment]
> Or `system_hw` doesn't have the correct value?

That's the thing I'm suspecting too. I'll investigate further.

**Comment by meleu** [comment]
@leiradel yeah, looks like something with `system_hw`...

In `libretro.c` the `system_hw` seems to be filled [here](https://github.com/libretro/Genesis-Plus-GX/blob/f5eed5133101999e1f6f04d2240ae77bb891adb9/libretro/libretro.c#L943-L960), and I don't see a `case` clause for `SYSTEM_SMS`.

**Comment by leiradel** [comment]
`system_bios` looks like a better place to check the system.

**Comment by meleu** [comment]
I've just tested and the same issue happens with picodrive. I'll try some tests...

**Comment by meleu** [comment]
Alright, I realized that the best heuristic approach is to use the file extension, just like RAMeka (the standalone RAEmu) does. Submitting a PR.
